---
# file: ansible/roles/php7.1/tasks/check_vars.yml

- name: check required variables are set
  fail:
    msg: "{{ item }} is not defined"
  when: item not in hostvars[inventory_hostname]
  with_items:
    - php_memory_limit